version: '3'
services:
  app:
    image: rrinatmahmutt/devops-for-programmers-project-74
    depends_on:
      db:
        condition: service_healthy
    command: make test

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    