name: Push
on:
    push:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DATABASE_HOST=${{ secrets.db_host }}" >> .env
          echo "DATABASE_NAME=${{ secrets.db_name }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.db_user }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.password }}" >> .env

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Run tests
        run: make docker-test
        
      - name: Build and push
        run: |
          docker-compose -f docker-compose.yml build app
          docker-compose -f docker-compose.yml push app